# Generated by Django 4.1.1 on 2022-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
                ('by', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('text', models.TextField()),
                ('dead', models.BooleanField()),
                ('parent', models.PositiveIntegerField()),
                ('poll', models.PositiveIntegerField()),
                ('kids', models.TextField()),
                ('url', models.URLField()),
                ('score', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('parts', models.TextField()),
                ('descendants', models.PositiveIntegerField()),
            ],
        ),
    ]
